// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7UEk9bTZNMqQZWKg9WFDGD6lTFTlKq0',
    appId: '1:447601770267:web:26e3119cd07ed090a8ddbe',
    messagingSenderId: '447601770267',
    projectId: 'catcare-3b18c',
    authDomain: 'catcare-3b18c.firebaseapp.com',
    storageBucket: 'catcare-3b18c.appspot.com',
    measurementId: 'G-JZTR8XESYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj29UV-KgtGJcfc7Uer3_is9sPfv8OP6I',
    appId: '1:447601770267:android:eae3bc8befe85710a8ddbe',
    messagingSenderId: '447601770267',
    projectId: 'catcare-3b18c',
    storageBucket: 'catcare-3b18c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_Wvixxwo5ixcsuqZ4i_UsUR_n9nQ-Qk',
    appId: '1:447601770267:ios:ab3421f265e5cd2ca8ddbe',
    messagingSenderId: '447601770267',
    projectId: 'catcare-3b18c',
    storageBucket: 'catcare-3b18c.appspot.com',
    iosBundleId: 'com.example.catcareFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ_Wvixxwo5ixcsuqZ4i_UsUR_n9nQ-Qk',
    appId: '1:447601770267:ios:ab3421f265e5cd2ca8ddbe',
    messagingSenderId: '447601770267',
    projectId: 'catcare-3b18c',
    storageBucket: 'catcare-3b18c.appspot.com',
    iosBundleId: 'com.example.catcareFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn7UEk9bTZNMqQZWKg9WFDGD6lTFTlKq0',
    appId: '1:447601770267:web:b352336776a3c146a8ddbe',
    messagingSenderId: '447601770267',
    projectId: 'catcare-3b18c',
    authDomain: 'catcare-3b18c.firebaseapp.com',
    storageBucket: 'catcare-3b18c.appspot.com',
    measurementId: 'G-RQYFD8D1VT',
  );
}
