package io.flutter.plugins

import androidx.annotation.Keep

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
object GeneratedPluginRegistrant {
    private const val TAG = "GeneratedPluginRegistrant"
    fun registerWith(@NonNull flutterEngine: FlutterEngine) {
        try {
            flutterEngine.getPlugins().add(FlutterFirebaseFirestorePlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin cloud_firestore, io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin",
                e
            )
        }
        try {
            flutterEngine.getPlugins().add(FlutterFirebaseAuthPlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin firebase_auth, io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin",
                e
            )
        }
        try {
            flutterEngine.getPlugins().add(FlutterFirebaseCorePlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin firebase_core, io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin",
                e
            )
        }
    }
}